import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { Button } from '../../components/Button';
import { TextInput } from '../../components/Field';
import { emailSchema, otpSchema } from './validation';
import { useSignup } from './SignupContext';
const DEMO_OTP = '123456';
export function EmailStage() { const { data, update, setStage } = useSignup(); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: zodResolver(emailSchema), mode: 'onBlur', defaultValues: { email: data.email } }); return <main className="shell narrow"><section className="card"><p className="eyebrow">Login / Signup</p><h1>Start with your email</h1><p className="muted">We’ll simulate a verification code. No backend, secrets, or real email delivery.</p><form onSubmit={handleSubmit(async (v) => { await new Promise((r) => setTimeout(r, 700)); update({ email: v.email.trim() }); toast.success('Demo verification code ready: 123456'); setStage('otp'); })}><TextInput id="email" label="Email" type="email" autoComplete="email" maxLength={120} error={errors.email?.message} {...register('email')} /><div className="actions"><Button loading={isSubmitting}>Send code</Button><Button type="button" variant="ghost" onClick={() => setStage('terms')}>Back</Button></div></form></section></main>; }
export function OtpStage() { const { setStage } = useSignup(); const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm({ resolver: zodResolver(otpSchema), mode: 'onChange', defaultValues: { otp: '' } }); return <main className="shell narrow"><section className="card"><p className="eyebrow">Verification</p><h1>Enter your 6-digit code</h1><p className="muted">Use demo OTP <strong>123456</strong> to continue.</p><form onSubmit={handleSubmit(async ({ otp }) => { await new Promise((r) => setTimeout(r, 650)); if (otp !== DEMO_OTP) { setError('otp', { message: 'That code does not match the demo OTP.' }); toast.error('Invalid verification code.'); return; } toast.success('Email verified. Build your profile.'); setStage('wizard'); })}><TextInput id="otp" label="Verification code" inputMode="numeric" maxLength={6} error={errors.otp?.message} {...register('otp', { onChange: (e) => { e.target.value = e.target.value.replace(/\D/g, '').slice(0, 6); } })} /><div className="actions"><Button loading={isSubmitting}>Verify</Button><Button type="button" variant="ghost" onClick={() => setStage('email')}>Back</Button></div></form></section></main>; }
