import { zodResolver } from '@hookform/resolvers/zod';
import { useEffect, type ReactNode } from 'react';
import { Controller, useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { Button } from '../../components/Button';
import { Select, TextArea, TextInput } from '../../components/Field';
import { locationData, states } from '../../data/locations';
import { useSignup } from './SignupContext';
import { campusSchema, identitySchema, reviewSchema, vibeSchema } from './validation';
const interests = ['House parties', 'Live music', 'Brunch', 'Study breaks', 'Sports', 'Art nights', 'Networking', 'Dancing'];
const vibes = ['High-energy parties', 'Small-group hangs', 'Creative events', 'Wellness socials'];
const vis = ['Campus only', 'Friends of friends', 'Public event hosts'];
export function Wizard() { const { step } = useSignup(); return <main className="shell"><section className="wizard"><Progress />{step === 0 && <Identity />}{step === 1 && <Campus />}{step === 2 && <Vibe />}{step === 3 && <Review />}</section></main>; }
function Progress() { const { step } = useSignup(); return <div className="progress" aria-label="Signup progress">{['Identity','Campus','Vibe','Review'].map((s,i)=><div key={s} className={i<=step?'active':''}><span>{i+1}</span>{s}</div>)}</div>; }
function Identity() { const { data, update, setStep, setStage } = useSignup(); const f = useForm({ resolver: zodResolver(identitySchema), mode: 'onBlur', defaultValues: data }); return <Card title="Build your profile" eyebrow="Step 1 of 4"><form onSubmit={f.handleSubmit(async(v)=>{ update(v); await delay(); setStep(1); })}><div className="grid two"><TextInput id="firstName" label="First name" maxLength={40} error={f.formState.errors.firstName?.message} {...f.register('firstName')} /><TextInput id="lastName" label="Last name" maxLength={40} error={f.formState.errors.lastName?.message} {...f.register('lastName')} /></div><div className="grid two"><TextInput id="age" label="Age" inputMode="numeric" maxLength={2} error={f.formState.errors.age?.message} {...f.register('age',{onChange:e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,2)}})} /><TextInput id="pronouns" label="Pronouns" placeholder="she/her, he/him, they/them" maxLength={30} error={f.formState.errors.pronouns?.message} {...f.register('pronouns')} /></div><TextArea id="bio" label="Short bio" maxLength={160} hint="160 characters max" error={f.formState.errors.bio?.message} {...f.register('bio')} /><Actions loading={f.formState.isSubmitting} back={() => setStage('otp')} /></form></Card>; }
function Campus() { const { data, update, setStep } = useSignup(); const f = useForm({ resolver: zodResolver(campusSchema), mode: 'onBlur', defaultValues: data }); const state = f.watch('state'); const available = state && state in locationData ? locationData[state as keyof typeof locationData] : undefined; useEffect(()=>{ if (available && !available.cities.includes(f.getValues('city'))) f.setValue('city',''); if (available && !available.colleges.includes(f.getValues('college'))) f.setValue('college',''); },[available, f]); return <Card title="Where do you go out?" eyebrow="Step 2 of 4"><form onSubmit={f.handleSubmit(async(v)=>{ update(v); await delay(); setStep(2); })}><Select id="state" label="State" options={states} error={f.formState.errors.state?.message} {...f.register('state')} /><div className="grid two"><Select id="city" label="City" options={available?.cities ?? []} disabled={!available} error={f.formState.errors.city?.message} {...f.register('city')} /><Select id="college" label="College" options={available?.colleges ?? []} disabled={!available} error={f.formState.errors.college?.message} {...f.register('college')} /></div><TextInput id="graduationYear" label="Graduation year" inputMode="numeric" maxLength={4} error={f.formState.errors.graduationYear?.message} {...f.register('graduationYear',{onChange:e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,4)}})} /><Actions loading={f.formState.isSubmitting} back={() => setStep(0)} /></form></Card>; }
function Vibe() { const { data, update, setStep } = useSignup(); const f = useForm({ resolver: zodResolver(vibeSchema), mode: 'onChange', defaultValues: data }); return <Card title="Tune your social signal" eyebrow="Step 3 of 4"><form onSubmit={f.handleSubmit(async(v)=>{ update(v); await delay(); setStep(3); })}><Controller control={f.control} name="interests" render={({field})=><div className="field"><label>Pick 2–5 interests</label><div className="chips">{interests.map(i=><button type="button" key={i} className={field.value.includes(i)?'chip selected':'chip'} onClick={()=> field.onChange(field.value.includes(i)?field.value.filter((x:string)=>x!==i):[...field.value,i])}>{i}</button>)}</div>{f.formState.errors.interests && <p className="error">{f.formState.errors.interests.message}</p>}</div>} /><Select id="eventVibe" label="Preferred event vibe" options={vibes} error={f.formState.errors.eventVibe?.message} {...f.register('eventVibe')} /><Select id="visibility" label="Profile visibility" options={vis} error={f.formState.errors.visibility?.message} {...f.register('visibility')} /><Actions loading={f.formState.isSubmitting} back={() => setStep(1)} /></form></Card>; }
function Review() { const { data, update, setStep, setStage } = useSignup(); const f = useForm({ resolver: zodResolver(reviewSchema), mode: 'onChange', defaultValues: data }); return <Card title="Confirm and enter" eyebrow="Step 4 of 4"><div className="review"><p><b>{data.firstName} {data.lastName}</b>, {data.age}, {data.pronouns}</p><p>{data.college} · {data.city}, {data.state} · Class of {data.graduationYear}</p><p>{data.interests.join(' · ')}</p></div><form onSubmit={f.handleSubmit(async(v)=>{ update(v); await delay(900); toast.success('Profile completed.'); setStage('success'); })}><label className="check"><input type="checkbox" {...f.register('agreements')} /> I agree to the Extroverts community pledge.</label>{f.formState.errors.agreements && <p className="error">{f.formState.errors.agreements.message}</p>}<Actions loading={f.formState.isSubmitting} back={() => setStep(2)} label="Complete profile" /></form></Card>; }
function Card({ children, title, eyebrow }: { children: ReactNode; title: string; eyebrow: string }) { return <div className="card"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children}</div>; }
function Actions({ loading, back, label='Continue' }: { loading: boolean; back: () => void; label?: string }) { return <div className="actions"><Button loading={loading}>{label}</Button><Button type="button" variant="ghost" disabled={loading} onClick={back}>Back</Button></div>; }
const delay = (ms = 600) => new Promise((r) => setTimeout(r, ms));
